### ISSUE TITLE
I use the tinyflow  for the first time.There are many problems to be solved.

### ISSUE THREAD

**Issue by MrNoBodyToEVO** [geowurster/tinyflow#8]
I download the code and I copy this code from ReadMe to run like this:

from collections import Counter
from tinyflow.serial import ops, Pipeline
pipe = Pipeline() \
    | "Split line into words" >> ops.flatmap(lambda x: x.lower().split()) \
    | "Remove empty lines" >> ops.filter(bool) \
    | "Produce the 5 most common words" >> ops.counter(5) \
    | "Sort by frequency desc" >> ops.sort(key=lambda x: x[1], reverse=True)
with open('LICENSE.txt') as f:
    results = dict(pipe(f)) 

It reports errors:ModuleNotFoundError: No module named 'tinyflow.serial'
so where is module 'tinyflow.serial'?
I guess it need to install some module,and I try some CMDs from README,and when I try like this:
$ git clone https://github.com/geowurster/tinyflow.git
$ cd tinyflow
$ pip install -e .\[all\]
It report errors:Invalid requirement,parse error at '''[all\\]'''
what does 'pip install -e .\[all\]' mean?
shall I replace .\[all\] with something?With what?
I use python3.

**Comment by geowurster** [comment]
@MrNoBodyToEVO The code in the readme was outdated.  I just pushed a fix, so give it another shot.

I also added a [disclaimer](https://github.com/geowurster/tinyflow#should-i-use-this) to the readme.  This project is strictly experimental, does not have a stable API, and I do not have any intentions to continue working on it.  If you just want to play with this library that is fine, but I discourage relying on the library in any manner.

Try installing with just `$ pip install -e .` instead.  That tells `pip` to look in the current directory for something to install.  In this case it finds the `setup.py` and installs `tiny flow`.  The [`$ pip -e` flag](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs) means the Python code is linked rather than copied, so if you edit the files they you do not have to reinstall to execute your edits.

The `[all]` is a [`setuptools` "Extra"](https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras).  `setuptools` lets you add additional dependencies that may only be required for part pieces of a library to function properly.  It is common to see a [`test`](https://github.com/geowurster/tinyflow/blob/b5980be39bc725813b7c4dba2a0f861da945602d/setup.py#L48) extra that defines all of the dependencies required to execute the test suite.  `docs` extras are also pretty common.  If you wanted to install a package and the code dependencies required to run the test you would do:

```console
$ pip install package-name[tests]
```

The word `all` maps directly to the [`extras_require`](https://github.com/geowurster/tinyflow/blob/b5980be39bc725813b7c4dba2a0f861da945602d/setup.py#L55) argument in `setup.py`, and for this package it means install the package and *all* extras.
